apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-08T06:49:26Z"
  labels:
    app: mysvc
  name: mysvc
  namespace: default
  resourceVersion: "2130"
  uid: e89e4554-2279-47fb-920c-b996ed9119c9
spec:
  clusterIP: 10.108.73.61
  clusterIPs:
  - 10.108.73.61
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: react-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
